app/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    #path('', home, name="home"),
    path('', views.index, name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    url(r'^event/view/(?P<event_id>\d+)/$', views.event_view, name='event_view'),
    url(r'^event/delete/(?P<event_id>\d+)/$', views.event_delete, name='event_delete'),
    url(r'^userhome/(?P<subject_id>\d+)/$', views.subject_view, name='subject_view'),
    path('userhome/', views.userhome, name='userhome'),
    # path('userhome/', views.HomeView.as_view(template_name='userindex.html'), name='userhome'),
    path('instructions/', views.instructions, name='instructions'),
    path('about_us/', views.about_us, name='about_us'),
    path('my_subjects/', views.my_subjects, name='my_subjects'),
    path('user/profile/', views.profile, name='profile'),
    path('user/profile/notification/', views.notification, name='notification'),
    path('my_subjects/add_registered_subject/', views.add_registered_subject, name='add_registered_subject'),
    path('my_subjects/delete_registered_subject/', views.delete_registered_subject, name='delete_registered_subject'),
]

authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import *
from .forms import *
app_name='authentication'
urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_user, name="register"),
    path("logout/", LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path("password_reset/", PasswordResetView.as_view(template_name='accounts/password_reset.html', subject_template_name='accounts/subject.txt', html_email_template_name='accounts/password_reset_confirm_email.html'), name="password_reset"),
    path("password_reset/done/", PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',form_class=ForgetPasswordForm), name='password_reset_confirm'),
    path("reset/done/", PasswordResetCompleteView.as_view(template_name='accounts/reset_done.html'), name="reset_done"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from verify_email import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path("", include("authentication.urls")),
    path("", include("app.urls")),
    path("", include("django.contrib.auth.urls")),
]

templates/layouts/base-fullscreen.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- Primary Meta Tags -->
    <title>KGPExpress - {% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="/static/assets/bootstrap/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i"
    />
    <link
      rel="stylesheet"
      href="/static/assets/fonts/simple-line-icons.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css"
    />
    <link rel="stylesheet" href="/static/assets/css/smoothproducts.css" />
    <link rel="stylesheet" type="text/css" href="/static/assets/css/styles.css" />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
        crossorigin="anonymous">
    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}
  </head>

  <body class="{% block body_class %}{% endblock body_class %} min-vh-100 d-flex flex-column" style="font-size: small; background-color: #F6F6F6;">
    <nav
      class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar"
      style="box-shadow: 0px 0px 5px 0px var(--dark);padding: 8px;"

    >
      <div class="container">
        <a class="navbar-brand logo" href="/">KGPExpress</a>
        <button
          data-toggle="collapse"
          class="navbar-toggler"
          data-target="#navcol-1"
        >
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
              <a id="home" class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a id="instructions" class="nav-link" href="{% url 'app:instructions' %}">Instructions</a>
            </li>
            <li class="nav-item">
              <a id="about_us" class="nav-link" href="{% url 'app:about_us' %}">About Us</a>
            </li>
            <li class="nav-item">
              <a id="login" class="nav-link text-primary active" href="{% url 'authentication:login' %}">Log in</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock content %}

    <footer class="page-footer dark mt-auto">
      <!-- <div class="container">
        <div class="row" style="align-items: center; text-align: center">
          <div class="col-sm-3">
            <h5>Get started</h5>
          </div>
          <div class="col-sm-3">
            <h5>About Us</h5>
          </div>
          <div class="col-sm-3">
            <h5>Login</h5>
          </div>
          <div class="col-sm-3">
            <h5>Sign Up</h5>
          </div>
        </div>
      </div>
      <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Legal</h5>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div> -->
      <div class="footer-copyright">
        <p>KGP Express</p>
      </div>
    </footer>
    {% include 'includes/scripts.html' %}

    <script src="/static/assets/js/base_fullscreen.js"></script>
    <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}
  </body>
</html>

templates/layouts/base-loggedin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- Primary Meta Tags -->
    <title>KGPExpress - {% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="/static/assets/bootstrap/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i"
    />
    <link
      rel="stylesheet"
      href="/static/assets/fonts/simple-line-icons.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css"
    />
    <link rel="stylesheet" href="/static/assets/css/smoothproducts.css" />
    <link
      rel="stylesheet"
      type="text/css"
      href="/static/assets/css/styles.css"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
      integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
      crossorigin="anonymous"
    />
    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}
  </head>

  <body
    class="{% block body_class %}{% endblock body_class %} min-vh-100 d-flex flex-column"
    style="font-size: small;background-color: #F6F6F6;"
  >
    <nav
      class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar"
      style="box-shadow: 0px 0px 5px 0px var(--dark); padding: 8px"
    >
      <div class="container">
        <a class="navbar-brand logo" href="{% url 'app:userhome' %}"
          >KGPExpress</a
        >
        <button
          data-toggle="collapse"
          class="navbar-toggler"
          data-target="#navcol-1"
        >
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
              <a id="home" class="nav-link" href="{% url 'app:userhome' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a
                id="my_subjects"
                class="nav-link"
                href="{% url 'app:my_subjects' %}"
                >My Subjects</a
              >
            </li>
            <li class="nav-item">
              <a
                id="instructions"
                class="nav-link"
                href="{% url 'app:instructions' %}"
                >Instructions</a
              >
            </li>
            <li class="nav-item">
              <a id="about_us" class="nav-link" href="{% url 'app:about_us' %}"
                >About Us</a
              >
            </li>
          </ul>
            <ul class="nav navbar-nav">
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle text-primary active"
                id="navDropDownLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                data-target="#profileNavbarDropdown"
              >
                <i class="fa fa-user-circle fa-2x" aria-hidden="true" style="padding: 0px;"></i>
              </a>
              <div id="profileNavbarDropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navDropDownLink">
                <a class="dropdown-item" href="{% url 'app:profile' %}">
                  <i class="fa fa-cog" aria-hidden="true"></i> Account Setting</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'authentication:logout' %}">
                  <i class="fas fa-sign-out-alt"></i> Logout</a
                >
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock content %}

    <footer class="page-footer dark mt-auto">
      <!-- <div class="container">
        <div class="row" style="align-items: center; text-align: center">
          <div class="col-sm-3">
            <h5>Get started</h5>
          </div>
          <div class="col-sm-3">
            <h5>About Us</h5>
          </div>
          <div class="col-sm-3">
            <h5>Login</h5>
          </div>
          <div class="col-sm-3">
            <h5>Sign Up</h5>
          </div>
        </div>
      </div>
      <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Legal</h5>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div> -->
      <div class="footer-copyright">
        <p>KGP Express</p>
      </div>
    </footer>
    {% include 'includes/scripts.html' %}

    <script src="/static/assets/js/base_fullscreen.js"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}
  </body>
</html>