app/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    #path('', home, name="home"),
    path('', views.index, name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    url(r'^event/view/(?P<event_id>\d+)/$', views.event_view, name='event_view'),
    url(r'^event/delete/(?P<event_id>\d+)/$', views.event_delete, name='event_delete'),
    url(r'^userhome/(?P<subject_id>\d+)/$', views.subject_view, name='subject_view'),
    path('userhome/', views.userhome, name='userhome'),
    # path('userhome/', views.HomeView.as_view(template_name='userindex.html'), name='userhome'),
    path('instructions/', views.instructions, name='instructions'),
    path('about_us/', views.about_us, name='about_us'),
    path('my_subjects/', views.my_subjects, name='my_subjects'),
    path('user/profile/', views.profile, name='profile'),
    path('user/profile/notification/', views.notification, name='notification'),
    path('my_subjects/add_registered_subject/', views.add_registered_subject, name='add_registered_subject'),
    path('my_subjects/delete_registered_subject/', views.delete_registered_subject, name='delete_registered_subject'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from verify_email import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path("", include("authentication.urls")),
    path("", include("app.urls")),
    path("", include("django.contrib.auth.urls")),
]

app/models.py
from django.db import models
from django.urls import reverse
from authentication.models import CustomUser

class Subject(models.Model):
    subject_code = models.CharField(max_length=7)
    subject_name = models.CharField(max_length=120)
    teacher_name = models.CharField(max_length=100,blank=True)
    description = models.CharField(max_length=1000,blank=True)
    department = models.CharField(max_length=100)
    syllabus = models.TextField(blank=True)
    year = models.DecimalField(max_digits=4, decimal_places=0)
    ltp = models.CharField(max_length=10)
    credit = models.IntegerField()
    semester = models.CharField(max_length=10)
    subject_id = models.AutoField(primary_key=True)

    class Meta:
        managed = True
        db_table = 'subject'
        unique_together = (('subject_code', 'semester', 'year'),)

class Event(models.Model):
    event_name = models.CharField(max_length=50)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    description = models.CharField(max_length=1000,blank=True)
    is_recurring = models.BooleanField(default=False)
    event_id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=50)
    time_of_edit = models.DateTimeField()
    user = models.ForeignKey(CustomUser, models.DO_NOTHING)
    subject = models.ForeignKey(Subject, models.DO_NOTHING)

    class Meta:
        managed = True
        db_table = 'event'


class History(models.Model):
    time_of_edit = models.DateTimeField(primary_key=True)
    event_name = models.CharField(max_length=50)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    type = models.CharField(max_length=50)
    is_recurring = models.BooleanField(default=False)
    description = models.CharField(max_length=1000,blank=True)
    event_id = models.IntegerField()
    user = models.OneToOneField(CustomUser, models.DO_NOTHING)

    class Meta:
        managed = True
        db_table = 'history'
        unique_together = (('time_of_edit', 'user'),)


class RegisteredSubjects(models.Model):
    user = models.ForeignKey(CustomUser, models.DO_NOTHING)
    subject = models.ForeignKey(Subject, models.DO_NOTHING)

    class Meta:
        managed = True
        db_table = 'registered_subjects'
        unique_together = (('user', 'subject'),)


# class Event(models.Model):
#     title = models.CharField(max_length=200)
#     subject = models.CharField(max_length=50)
#     description = models.TextField()
#     start_time = models.DateTimeField()
#     end_time = models.DateTimeField()
#
#     @property
#     def get_html_url(self):
#         url = reverse('app:event_edit', args=(self.id,))
#         return f'<a href="{url}"> {self.title} </a>'

app/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from app.models import Event
from datetime import datetime, timedelta, date
from authentication.models import CustomUser

class SearchForm(forms.Form):
    subject = forms.CharField()
    semester = forms.CharField()
    year = forms.DecimalField()

class EventForm(ModelForm):
    event_name = forms.CharField
    start_time = forms.DateTimeField(widget = DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'))
    end_time = forms.DateTimeField(widget = DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'))
    description = forms.CharField
    # is_recurring = forms.BooleanField(initial=True, required=False)
    type = forms.CharField
    #time_of_edit = forms.DateTimeField(widget=DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'))

    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        fields = ('event_name','start_time','end_time','description','is_recurring','type')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

templates/event.html
{% extends request.user.is_authenticated|yesno:"layouts/base-loggedin.html,layouts/base-fullscreen.html" %}

{% block title %}Event{% endblock%}
{% block content %}
<div class="clearfix" style="padding-top: 55px">
  <a class="btn btn-primary left" href="{% url 'app:userhome' %}"><i class="fas fa-backward"></i> Calendar</a>
</div>

<section class="clean-block">
  <div class="container">
    <div class="card align-middle" style="width: fit-content; min-width: 50%;margin: auto;">
      <div class="card-header">
        <h5>
          Event Details
        </h5>
      </div>
      <div class="card-body">
        <table class="table table-responsive" style="width: 100%;">
          <tbody>
            <tr>
              <th class="social-label b-none p-t-0">
                Event Name
              </th>
              <td class="social-user-name b-none p-t-0">
                {{ event.event_name }}
              </td>
            </tr>
            <tr>
              <th class="social-label b-none p-t-0">
                Event Type
              </th>
              <td class="social-user-name b-none p-t-0">
                {{ event.type }}
              </td>
            </tr>
            <tr>
              <th class="social-label b-none p-t-0">
                Subject
              </th>
              <td class="social-user-name b-none p-t-0 ">
                {{ subject_name }}
              </td>
            </tr>
            <tr>
              <th class="social-label b-none p-t-0">
                Start Time
              </th>
              <td class="social-user-name b-none p-t-0">
                {{ event.start_time|default_if_none:"-" }}
              </td>
            </tr>
            <tr>
              <th class="social-label b-none p-t-0">
                End Time
              </th>
              <td class="social-user-name b-none p-t-0">
                {{ event.end_time|default_if_none:"-" }}
              </td>
            </tr>
            <tr>
              <th class="social-label b-none p-t-0">
                Recurring
              </th>
              <td class="social-user-name b-none p-t-0">
                {{ event.is_recurring|yesno:"Yes,No" }}
              </td>
            </tr>
            <tr>
              <th class="social-label b-none p-t-0">
                Description
              </th>
              <td class="social-user-name b-none p-t-0">
                {{ event.description }}
              </td>
            </tr>
          </tbody>
        </table>
        <div class="right">
          <a class="btn btn-primary left" href="{% url 'app:event_edit' event_id=event.event_id %}"><i
              class="fas fa-edit"></i></a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block javascripts %}
<script src="/static/assets/js/event.js"></script>
{% endblock javascripts %}

templates/event_add_and_edit.html
{% extends "layouts/base-loggedin.html" %} 
{% block title %}Event{% endblock%}
{% block content %}
<div class="clearfix" style="padding-top: 55px">
  <a class="btn btn-primary left" href="{% url 'app:userhome' %}"><i class="fas fa-backward"></i> Calendar</a>
  {% if event %}
  <a class="btn btn-primary right" href="{% url 'app:event_new' %}"><i class="fas fa-plus"></i> New Event</a>
  {% elif delete_flag %}
  <a class="btn btn-primary right" href="{% url 'app:event_new' %}"><i class="fas fa-plus"></i> New Event</a>
  {% endif %}
</div>

<section class="clean-block clean-form dark" style="background: transparent;">
<div class="container">
  {% if verification_status == False %}
  <div class="card">
    <div class="card-body text-center">
      <p>Please complete you profile to create and edit Events. Click here to complete <a href="{% url 'app:profile' %}" style="font-size: 14px;">Profile</a>.</p>
    </div>
  </div>
  {% elif delete_flag == True %}
  <div class="card">
    <div class="card-body text-center">
      <div class="text-danger">Event deleted !!!</div>
    </div>
  </div>
  {% else %}
    <form
      method="post"
      action="."
      style="
        border-radius: 10px;
        padding: 33px;
        border-color: rgb(255, 255, 255);
        font-size: 14px;
      "
    >
      {% csrf_token %}
      <h5 class="text-center">
        {% if event %}
          Edit Event
        {% else %}
          New Event
        {% endif %}
      </h5>
      <p style="text-align: center;font-size: 13px;">
        {% if msg %}
        <span style="color: green;">{{ msg | safe }}</span>
        {% endif %}
        {% if form.errors %} 
        {% for field in form %} 
        {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} 
        {% endfor %} 
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} 
        {% endif %}
    </p>

      <div class="form-group">
        <label for="id_Subject" >Subject</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"
              ><i class="fa fa-book" style="width: 16px"></i
            ></span>
          </div>
          <input
          type="text"
          id="id_subject"
          class="form-control"
          placeholder="Select course here"
          name="subject"
          list="subject-list"
          {% if subject %}
          value="{{subject.subject_code_name}}"
          readonly
          {% endif %}
          
        />
        {% if not subject %}
        <datalist id="subject-list"></datalist>
        {% endif %}
        </div>
      </div>

      <div class="form-group">
        <div class="form-row">
          <div class="col" style="width: 40%">
            <label>Semester</label>
            <select class="custom-select"
            name="semester"
            {% if subject %}
            disabled
            {% endif %}
            >
            {% if subject %}
            <option selected>{{subject.semester}}</option>
            {% else %}
            <option selected>Spring</option>
            <option>Autumn</option>
            {% endif %}
          </select>
          </div>
          <div class="col" style="width: 40%">
            <label>Year</label>
            <select class="custom-select" name="year" {% if subject %}disabled{% endif %}>
              {% if subject %}
              <option selected>{{subject.year}}</option>
              {% else %}
              <option selected>2021</option>
              <option>2020</option>
              {% endif %}
            </select>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="id_event_name" >Event name</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"
              ><i class="fa fa-sticky-note" style="width: 16px"></i
            ></span>
          </div>
          <input
            type="text"
            name="event_name"
            maxlength="50"
            id="id_event_name"
            class="form-control"
            placeholder="Event Name"
            {% if event %}
            value="{{ event.event_name }}"
            {% endif %}
            required
          />
        </div>
      </div>
      <div class="form-group">
        <label for="id_start_time" >Start Time</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-calendar-check-o" style="width: 16px"></i></span>
          </div>
          <input
            type="datetime-local"
            name="start_time"
            id="id_start_time"
            class="form-control"
            {% if event %}
            value="{{ event.start_time }}"
            {% endif %}
            required
          />
        </div>
      </div>
      <div class="form-group">
        <label for="id_end_time" >End Time</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-calendar-times-o" style="width: 16px"></i></span>
          </div>
          <input
            type="datetime-local"
            name="end_time"
            id="id_end_time"
            class="form-control"
            {% if event %}
            value="{{ event.end_time }}"
            {% endif %}
            required
          />
        </div>
      </div>
      <div class="form-group">
        <label for="id_description">Description</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"
              ><i class="fa fa-align-justify" style="width: 16px"></i
            ></span>
          </div>
          <textarea 
            class="form-control"
            type="text"
            name="description"
            maxlength="1000"
            id="id_description"
            placeholder="Description"
            rows="2"
          >{% if event %}{{ event.description }}{% endif %}</textarea>
        </div>
      </div>

      <div class="form-group">
        <label for="id_type">Type</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"
              ><i class="fa fa-filter " style="width: 16px"></i
            ></span>
          </div>
          <select
            class="form-control custom-select"
            name="type"
            id="id_type">
            <option selected value="Class Test">Class Test</option>
            <option value="Quiz">Quiz</option>
            <option value="Assignment">Assignment</option>
            <option value="Project">Project</option>
            <option value="Other">Other</option>
            {% if event %}
            <option selected value="{{event.type}}">{{event.type}}</option>
            {% endif %}
          </select>
        </div>
      </div>
      <!-- <div class="form-group">
        <label for="id_is_recurring">Is Recurring</label>
        <div class="input-group">
          <input class="form-check-input" type="checkbox" id="id_is_recurring" name="is_recurring" 
        {% if event.is_recurring %}
          checked
        {% endif %}
            />
        </div>
      </div> -->
      <div class="form-group form-check">
        <input class="form-check-input" type="checkbox" id="id_is_recurring" name="is_recurring" 
        {% if event.is_recurring %}
          checked
        {% endif %}
            /><label
          class="form-check-label"
          for="id_is_recurring"
          >Is Recurring</label
        >
      </div>
      {% if event %}
        <div class="row">
          <div class="col-6">
            <button class="btn btn-primary btn-block left" type="submit">
              <i class="fas fa-save    "></i> Submit
            </button>
          </div>
          <div class="col-6">
            <a class="btn btn-danger btn-block right" href="{% url 'app:event_delete' event_id=event.event_id %}"><i class="fas fa-trash"></i> Delete</a>
          </div>
        </div>
      {% else %}
      <button class="btn btn-primary btn-block" type="submit">
        <i class="fas fa-save    "></i>Submit
      </button>
      {% endif %}
      
    </form>
  {% endif %}
  </div>
</section>

{% endblock content %}


{% block javascripts %}
<script src="/static/assets/js/event.js"></script>
{% endblock javascripts %}

templates/my_subjects.html
{% extends "layouts/base-loggedin.html" %} 
{% block title %}My Subjects{%endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css"
  rel="stylesheet" />
<link href="/static/assets/css/fullcalendar.css" rel="stylesheet" />
<link href="/static/assets/css/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="/static/assets/css/index.css" rel="stylesheet" />
{% endblock stylesheets %} {% block body_class %} {%endblock body_class %}
{%block content %}

<main class="page landing-page" style="padding-top: 60px">
  <section class="clean-block payment-form dark">
    <table class="table">
      <tbody>
        <tr class="d-flex">
          <td class="col-8">
            <div class="container card" style="padding: 0px">
              <div class="card-body">
                <div class="card-title">
                  <h5>Schedule</h5>
                  <hr />
                </div>
                <div class="dark">
                  <div id="calendar"></div>
                  <div style="clear: both"></div>
                </div>
              </div>
            </div>
          </td>
          <td class="col-4">
            <div class="card" style="background-color: white; min-height: 100%;">
              <div class="card-body">
                <div class="card-title">
                  <h5>Registered Subjects</h5>
                  <hr />
                </div>
                <div>
                  <ul id="registered_subjects" class="list-group">
                    {% for sub in registered_subjects %}

                    <li id="{{sub.subject_id}}" class="list-group-item">
                      <div class="row">
                        <div class="col-10">
                          <a class="btn btn-sm text-truncate btn-block text-left" href="{% url 'app:subject_view' subject_id=sub.subject_id %}">
                            {{sub.subject_code}}: {{sub.subject_name}}
                          </a>
                        </div>
                        <div class="col-2">
                          <a type="button"  class="btn btn-sm text-truncate btn-block text-left" data-toggle="modal"
                          data-target="#DeleteSubjectModal{{sub.subject_id}}"><i class="fa fa-trash"
                              aria-hidden="true"></i></a>
                        </div>
                      </div>
                    </li>

                    {% endfor %}
                  </ul>
                </div>
                <br />
                <button type="button" class="btn btn-outline-dark btn-sm pull-right" data-toggle="modal"
                  data-target="#AddSubjectModal">
                  <i class="fas fa-plus"> Add Subject</i>
                </button>
              </div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </section>
  <div class="modal fade" id="AddSubjectModal" data-backdrop="static" data-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Add Subject</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form id="addRegisteredSubjectForm" method="post" style="border-radius: 10px; border-color: rgb(255, 255, 255)">
          {% csrf_token %}
          <div class="modal-body">
            <div class="form-group">
              <label for="card-holder">Subject</label>
              <input type="text" id="subject" class="form-control" placeholder="Enter course code" name="subject"
                list="subject-list" required />
              <datalist id="subject-list"></datalist>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">
                Close
              </button>
              <button type="submit" class="btn btn-primary" name="addRegisteredSubject"
                value="addRegisteredSubjectFormSubmit">
                Submit
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% for sub in registered_subjects %}
  <div class="modal fade" id="DeleteSubjectModal{{sub.subject_id}}" data-backdrop="static" data-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Delete Subject</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form id="deleteRegisteredSubjectForm{{sub.subject_id}}" method="post" style="border-radius: 10px; border-color: rgb(255, 255, 255)">
          {% csrf_token %}
          <div class="modal-body">
            <p>Are You Sure Want to remove '{{sub.subject_code}}: {{sub.subject_name}}' from your subjects?</p>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">
                Close
              </button>
              <button type="submit" class="btn btn-danger" name="deleteRegisteredSubject"
                value="deleteRegisteredSubjectFormSubmit">
                Remove
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endfor %}
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
  var data = String("{{ event }}");
  var event_list;
  function data_update() {
    event_list = eval(data.replace(/&quot;/g, '"'));
  }
  data_update(data);

  // {#console.log(data)#}
  // {#console.log(event_list)#}
</script>
<script
  src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@master/dist/latest/bootstrap-autocomplete.min.js"></script>
<script src="/static/assets/js/fullcalendar.js" type="text/javascript"></script>
<script src="/static/assets/js/calender.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
<script src="/static/assets/js/my_subjects.js"></script>
<script src="/static/assets/js/csrf_handling.js"></script>
{% endblock javascripts %}

templates/userindex.html
{% extends "layouts/base-loggedin.html" %} {% block title %}Home{% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"
/>
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css"
  rel="stylesheet"
/>
<link href="/static/assets/css/fullcalendar.css" rel="stylesheet" />
<link
  href="/static/assets/css/fullcalendar.print.css"
  rel="stylesheet"
  media="print"
/>
<link href="/static/assets/css/index.css" rel="stylesheet" />
{% endblock stylesheets %} {% block body_class %} {%endblock body_class %}
{%block content %}

<main class="page landing-page" style="padding-top: 60px">
  <section class="clean-block payment-form" style="padding-bottom: 10px">
    <div class="container" style="padding-top: 25px">
      <form name="form" method="get" action="" style="max-width: 100%">
        {% csrf_token %}

        <div class="card-details" style="padding: 15px; padding-bottom: 5px">
          <h3 class="title">Subject Details</h3>

          <div class="form-row">
            <div class="col-sm-7">
              <div class="form-group">
                <label for="card-holder">Subject</label>
                <input
                  type="text"
                  id="subject"
                  class="form-control"
                  placeholder="Enter course code"
                  name="subject"
                  list="subject-list"
                />
                <datalist id="subject-list"></datalist>
              </div>
            </div>
            <div class="col-sm-5">
              <div class="form-group">
                <div class="form-row">
                  <div class="col" style="width: 35%">
                    <label>Semester</label>
                    <select class="custom-select" name="semester">
                      <option selected>Spring</option>
                      <option>Autumn</option>
                    </select>
                  </div>
                  <div class="col" style="width: 35%">
                    <label>Year</label>
                    <select class="custom-select" name="year">
                      <option selected>2021</option>
                      <option>2020</option>
                    </select>
                  </div>
                  <div class="col" style="width: 25%">
                    <div class="form-group">
                      <button
                        class="btn btn-primary btn-block"
                        type="submit"
                        style="
                          margin: 0px;
                          padding: 6px;
                          position: absolute;
                          bottom: 0px;
                          width: 95%;
                        "
                      >
                        Search
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </section>


  <section>
    <div class="container card" style="padding: 0px">
      <!-- <div class="container" > -->
      <div class="card-body">
        
      <div class="card-title">  
      <div class="row">
          <div class="col-9">{% if subject %}<h5 class="text-left">{{ subject }}</h5>{% endif %}</div>
          <div class="col-3 d-flex justify-content-end">
            <a class="btn btn-sm btn-outline-primary" href="{% url 'app:event_new' %}" style="height: fit-content;"><i class="fa fa-plus" ></i>Add Event</a>
          </div>
      </div>
      <hr />
      </div>
        
        <div class="dark">
          <div id="calendar"></div>
          <div style="clear: both"></div>
        </div>
      </div>
    </div>
  </section>
  {% if search_result == True %}
  <section style="margin: 10px">
    <div class="card container text-left">
      <div class="card-body">
        <div class="card-title">
          <h4>Subject Details</h4>
        </div>
        <table class="table table-responsive m-b-0">
          <tbody>
            {% for k,v in subject_details.items %}
            <tr>
              <th class="social-label b-none">{{k}}</th>
              <td class="social-user-name b-none text-muted">{{v}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
  {% endif %}

</main>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
  var data = String("{{ event }}");
  var event_list;
  function data_update(){
    event_list = eval(data.replace(/&quot;/g, '"'));
  }
  data_update(data);
  console.log(event_list)

  // {#console.log(data)#}
  // {#console.log(event_list)#}
</script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@master/dist/latest/bootstrap-autocomplete.min.js"></script>
<script src="/static/assets/js/simple_coloring_script.js"></script>
<script src="/static/assets/js/fullcalendar.js" type="text/javascript"></script>
<script src="/static/assets/js/calender.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
{% endblock javascripts %}